services:
  wordpress:
    image: wordpress:php8.1
    container_name: wordpress_mob
    mem_limit: 1024m
    #cpus: 0.5
    restart: unless-stopped
    ports:
      - "9001:80"
    environment:
      WORDPRESS_DB_HOST: mysql_mob
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wpassword
      WORDPRESS_DB_NAME: wordpress_mob
      #WORDPRESS_CONFIG_EXTRA: |
        #define('WP_HOME'https://server-ip:8081');
        #define('WP_SITEURL','https://server-ip:8081');
    volumes:
      - ./html:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_mob
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress_mob
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wpassword
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
